# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

uP <- function(mloc, mpar) {
    .Call('_cdmTools_uP', PACKAGE = 'cdmTools', mloc, mpar)
}

ObsLogLik <- function(mpar, mX, vlogPrior, vgroup, mloc, weights) {
    .Call('_cdmTools_ObsLogLik', PACKAGE = 'cdmTools', mpar, mX, vlogPrior, vgroup, mloc, weights)
}

LikNR <- function(mpar, mX, vlogPrior, vgroup, mloc, weights, simplify = TRUE) {
    .Call('_cdmTools_LikNR', PACKAGE = 'cdmTools', mpar, mX, vlogPrior, vgroup, mloc, weights, simplify)
}

LikNR_LC <- function(mP, mX, vlogPrior, vgroup, weights, simplify = 1L) {
    .Call('_cdmTools_LikNR_LC', PACKAGE = 'cdmTools', mP, mX, vlogPrior, vgroup, weights, simplify)
}

Lik_DTM <- function(mP, mX, vC, vlogPrior) {
    .Call('_cdmTools_Lik_DTM', PACKAGE = 'cdmTools', mP, mX, vC, vlogPrior)
}

Lik_DTM_MG <- function(mP, mX, vC, vlogPrior, vgroup) {
    .Call('_cdmTools_Lik_DTM_MG', PACKAGE = 'cdmTools', mP, mX, vC, vlogPrior, vgroup)
}

combnCpp <- function(n, k) {
    .Call('_cdmTools_combnCpp', PACKAGE = 'cdmTools', n, k)
}

rowProd <- function(m, v) {
    .Call('_cdmTools_rowProd', PACKAGE = 'cdmTools', m, v)
}

whichrow_AinB <- function(A, B) {
    .Call('_cdmTools_whichrow_AinB', PACKAGE = 'cdmTools', A, B)
}

whichcol_AinB <- function(A, B) {
    .Call('_cdmTools_whichcol_AinB', PACKAGE = 'cdmTools', A, B)
}

unique_rows <- function(A) {
    .Call('_cdmTools_unique_rows', PACKAGE = 'cdmTools', A)
}

alpha2 <- function(K) {
    .Call('_cdmTools_alpha2', PACKAGE = 'cdmTools', K)
}

alphap <- function(maxlevel) {
    .Call('_cdmTools_alphap', PACKAGE = 'cdmTools', maxlevel)
}

ColNormalize <- function(X) {
    .Call('_cdmTools_ColNormalize', PACKAGE = 'cdmTools', X)
}

RowNormalize <- function(X) {
    .Call('_cdmTools_RowNormalize', PACKAGE = 'cdmTools', X)
}

Pr_2PL <- function(theta, a, b) {
    .Call('_cdmTools_Pr_2PL', PACKAGE = 'cdmTools', theta, a, b)
}

Pr_2PL_vec <- function(theta, a, b, minvalue = 1e-16, maxvalue = 1 - 1e-16) {
    .Call('_cdmTools_Pr_2PL_vec', PACKAGE = 'cdmTools', theta, a, b, minvalue, maxvalue)
}

logLikPattern <- function(AlphaPattern, theta, a, b) {
    .Call('_cdmTools_logLikPattern', PACKAGE = 'cdmTools', AlphaPattern, theta, a, b)
}

PostTheta <- function(AlphaPattern, theta, f_theta, a, b) {
    .Call('_cdmTools_PostTheta', PACKAGE = 'cdmTools', AlphaPattern, theta, f_theta, a, b)
}

expectedNR <- function(AlphaPattern, nc, theta, f_theta, a, b) {
    .Call('_cdmTools_expectedNR', PACKAGE = 'cdmTools', AlphaPattern, nc, theta, f_theta, a, b)
}

logP_AlphaPattern <- function(AlphaPattern, theta, f_theta, a, b) {
    .Call('_cdmTools_logP_AlphaPattern', PACKAGE = 'cdmTools', AlphaPattern, theta, f_theta, a, b)
}

HoIRTlogLik <- function(AlphaPattern, ns, theta, f_theta, a, b) {
    .Call('_cdmTools_HoIRTlogLik', PACKAGE = 'cdmTools', AlphaPattern, ns, theta, f_theta, a, b)
}

HoIRTlogLik3 <- function(ns, mX, theta, f_theta, a, b) {
    .Call('_cdmTools_HoIRTlogLik3', PACKAGE = 'cdmTools', ns, mX, theta, f_theta, a, b)
}

incomplogL <- function(a, b, logL, AlphaPattern, theta, f_theta) {
    .Call('_cdmTools_incomplogL', PACKAGE = 'cdmTools', a, b, logL, AlphaPattern, theta, f_theta)
}

designM <- function(Kj, rule, AlphaPattern = NULL) {
    .Call('_cdmTools_designM', PACKAGE = 'cdmTools', Kj, rule, AlphaPattern)
}

matchMatrix <- function(A, B) {
    .Call('_cdmTools_matchMatrix', PACKAGE = 'cdmTools', A, B)
}

eta <- function(Q, AlphaPattern = NULL) {
    .Call('_cdmTools_eta', PACKAGE = 'cdmTools', Q, AlphaPattern)
}

item_latent_group <- function(Q, AlphaPattern = NULL) {
    .Call('_cdmTools_item_latent_group', PACKAGE = 'cdmTools', Q, AlphaPattern)
}

